/*
* UNIVERSIDAD DE LAS FUERZAS ARMADAS ESPE
* RECURSIVIDAD CON CLASES
* NOMBRE: GUALOTUÑA OMAR, CHASILUISA SANTIAGO
* FECHA DE CREACION: 2022/05/16
* FECHA DE MODIFICACION: 2022/05/16
* VERSION 1
* ESTRUCTURA DE DATOS
* NRC: 4683
*/
#pragma once
#include<iostream>

class Factorial {
	public:
		int factorial(int);
};

