/*
* UNIVERSIDAD DE LAS FUERZAS ARMADAS ESPE
* PROGRAMA PARA REALIZAR LA TORRE DE HANOI CON RECURSIVIDAD
* NOMBRE: GUALOTUÑA OMAR, CHASILUISA SANTIAGO
* FECHA DE CREACION: 2022/05/19
* FECHA DE MODIFICACION: 2022/05/19
* VERSION 1
* ESTRUCTURA DE DATOS
* NRC: 4683
*/
#pragma once
#include<iostream>

template <class T>

class TorreHanoi{
	public:
		void torreDeHanoi(T,T,T,T);
};
