/*
* UNIVERSIDAD DE LAS FUERZAS ARMADAS ESPE
* FUNCION PARA OBTENER EL MCD Y MCM DE DOS NUMEROS CON RECURSIVIDAD
* NOMBRE: GUALOTUÑA OMAR, CHASILUISA SANTIAGO
* FECHA DE CREACION: 2022/05/19
* FECHA DE MODIFICACION: 2022/05/19
* VERSION 1
* ESTRUCTURA DE DATOS
* NRC: 4683
*/
#pragma once
#include<iostream>

template <class T>

class MinimoComunMultiplo {
	public:
		T mcm(T,T);
};
